/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/[communityId]/': RouteRecordInfo<'/dashboard/[communityId]/', '/dashboard/:communityId', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/dashboard/[communityId]/community/': RouteRecordInfo<'/dashboard/[communityId]/community/', '/dashboard/:communityId/community', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/dashboard/[communityId]/role/': RouteRecordInfo<'/dashboard/[communityId]/role/', '/dashboard/:communityId/role', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/dashboard/[communityId]/shop/': RouteRecordInfo<'/dashboard/[communityId]/shop/', '/dashboard/:communityId/shop', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/dashboard/[communityId]/user/': RouteRecordInfo<'/dashboard/[communityId]/user/', '/dashboard/:communityId/user', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
  }
}
